import { Profile } from "./types";

export const mockProfiles: Profile[] = [
  {
    id: "1",
    name: "MSP",
    gender: "Male",
    age: 29,
    height: "5'4",
    residence: "New York, NY",
    relocate: "Open - preference for Chicago, New York, or Texas",
    education:
      "Masters in Supply Chain and Operations Management from University of Illinois at Chicago. Bachelors in Business Administration from Bahria University Karachi.",
    profession:
      "Worked as a logistics coordinator in a fine arts freight forwarding company post graduation. Currently working at a gas station in NY.",
    legalStatus: "Pending green card",
    maritalStatus: "Divorced",
    children: "None",
    ethnicity: "Punjabi (family background), Pakistani (born and raised in Karachi)",
    religiousSect: "Sunni",
    languages: ["Urdu", "English"],
    lookingFor: {
      ageRange: "Around 29",
      height: "Around 5'4",
      ethnicity: "Pakistani / Indian",
      residence: "Anywhere",
      legalStatus: "US Citizen or legal resident",
      maritalStatus: "Single / Divorced / Widowed",
      religiousSect: "Sunni",
    },
    comments:
      "I'm looking for more of a companion and friend who is faithful and fun loving, constantly works on improving religiously, takes husband wife relationship seriously and for the sake of Allah, knows own responsibility and rights of each other for a healthy relationship and tries to balance life in every aspect, and stands by in every part of life both good times and hardships.",
    aboutMe:
      "I'm a single child of my parents, Alhumdullilah by the grace of Allah I try to be punctual about my prayers mostly in masjid, I don't take life too seriously, enjoy life in every and by every halal means, easy going person.",
    contactName: "Cousin Sister",
    contactPhone: "347-341-0176",
    createdAt: "2025-04-20",
    verified: true,
    phoneVerified: true,
    adminVerified: true,
  },
  {
    id: "2",
    name: "Fatima K.",
    gender: "Female",
    age: 26,
    height: "5'3",
    residence: "Chicago, IL",
    relocate: "Open to relocation",
    education: "Bachelors in Computer Science from DePaul University",
    profession: "Software Engineer at a tech company in Chicago",
    legalStatus: "US Citizen",
    maritalStatus: "Single",
    children: "None",
    ethnicity: "Pakistani (Karachi)",
    religiousSect: "Sunni",
    languages: ["Urdu", "English"],
    lookingFor: {
      ageRange: "26-32",
      height: "5'6 or taller",
      ethnicity: "Pakistani / Indian",
      residence: "US based",
      legalStatus: "US Citizen or Green Card holder",
      maritalStatus: "Single",
      religiousSect: "Sunni",
    },
    comments:
      "Looking for someone who is practicing, family-oriented, and has good character. Someone who balances deen and dunya well.",
    aboutMe:
      "Practicing Muslimah who loves to cook, read, and spend time with family. Active in my local community and mosque. Value education and personal growth.",
    contactName: "Mother",
    contactPhone: "312-555-0199",
    createdAt: "2025-04-18",
    verified: true,
    phoneVerified: true,
    adminVerified: true,
  },
  {
    id: "3",
    name: "Ahmed R.",
    gender: "Male",
    age: 31,
    height: "5'10",
    residence: "Houston, TX",
    relocate: "Prefer Texas",
    education:
      "Masters in Electrical Engineering from University of Houston. Bachelors from NUST Islamabad.",
    profession: "Senior Engineer at an oil & gas company",
    legalStatus: "Green Card holder",
    maritalStatus: "Single",
    children: "None",
    ethnicity: "Pathan, Pakistani (from Peshawar)",
    religiousSect: "Sunni",
    languages: ["Pashto", "Urdu", "English"],
    lookingFor: {
      ageRange: "24-29",
      height: "5'2 - 5'6",
      ethnicity: "Pakistani",
      residence: "US based",
      legalStatus: "Any",
      maritalStatus: "Single",
      religiousSect: "Sunni",
    },
    comments:
      "Looking for a practicing Muslimah who values family, is kind-hearted, and supportive. Someone who wants to build a life together based on Islamic principles.",
    aboutMe:
      "Alhamdulillah, I pray five times daily and try to attend Fajr at the masjid. I enjoy outdoor activities, hiking, and traveling. Family is very important to me.",
    contactName: "Father",
    contactPhone: "832-555-0177",
    createdAt: "2025-04-15",
    verified: false,
    phoneVerified: true,
    adminVerified: false,
  },
  {
    id: "4",
    name: "Aisha M.",
    gender: "Female",
    age: 24,
    height: "5'5",
    residence: "Dallas, TX",
    relocate: "Open to relocation within US",
    education: "Bachelors in Nursing from UT Arlington",
    profession: "Registered Nurse at a hospital in Dallas",
    legalStatus: "US Citizen",
    maritalStatus: "Single",
    children: "None",
    ethnicity: "Indian (Hyderabadi)",
    religiousSect: "Sunni",
    languages: ["Urdu", "Hindi", "English"],
    lookingFor: {
      ageRange: "26-33",
      height: "5'8 or taller",
      ethnicity: "Indian / Pakistani",
      residence: "US based",
      legalStatus: "US Citizen or Green Card holder",
      maritalStatus: "Single",
      religiousSect: "Sunni",
    },
    comments:
      "Seeking a partner who is God-fearing, respectful, and family-oriented. Someone who understands the importance of communication and is willing to grow together in faith.",
    aboutMe:
      "Alhamdulillah, I am a practicing Muslimah. I love my profession and caring for others. In my free time, I enjoy reading Islamic books, cooking, and spending time with family.",
    contactName: "Father",
    contactPhone: "469-555-0188",
    createdAt: "2025-04-12",
    verified: true,
    phoneVerified: true,
    adminVerified: true,
  },
  {
    id: "5",
    name: "Omar S.",
    gender: "Male",
    age: 28,
    height: "5'11",
    residence: "Jersey City, NJ",
    relocate: "Open - NY/NJ area preferred",
    education: "Bachelors in Finance from Rutgers University",
    profession: "Financial Analyst at a bank in Manhattan",
    legalStatus: "US Citizen",
    maritalStatus: "Single",
    children: "None",
    ethnicity: "Bengali (from Dhaka)",
    religiousSect: "Sunni",
    languages: ["Bengali", "English"],
    lookingFor: {
      ageRange: "23-28",
      height: "5'2 - 5'5",
      ethnicity: "Bengali / South Asian",
      residence: "Northeast US",
      legalStatus: "US Citizen or Green Card holder",
      maritalStatus: "Single",
      religiousSect: "Sunni",
    },
    comments:
      "Looking for someone humble, caring, and who puts their trust in Allah. Wants to build a home filled with love, respect, and Islamic values.",
    aboutMe:
      "Born and raised in the US. Active in my local masjid and youth group. I enjoy playing soccer, reading, and volunteering. I value honesty and good character above all.",
    contactName: "Mother",
    contactPhone: "201-555-0166",
    createdAt: "2025-04-10",
    verified: true,
    phoneVerified: true,
    adminVerified: true,
  },
  {
    id: "6",
    name: "Mariam J.",
    gender: "Female",
    age: 27,
    height: "5'2",
    residence: "Los Angeles, CA",
    relocate: "Prefer West Coast",
    education: "Masters in Public Health from UCLA",
    profession: "Public Health Researcher",
    legalStatus: "US Citizen",
    maritalStatus: "Single",
    children: "None",
    ethnicity: "Pakistani (Lahore)",
    religiousSect: "Sunni",
    languages: ["Punjabi", "Urdu", "English"],
    lookingFor: {
      ageRange: "27-34",
      height: "5'7 or taller",
      ethnicity: "Pakistani / South Asian",
      residence: "US based",
      legalStatus: "US Citizen or Green Card holder",
      maritalStatus: "Single / Divorced",
      religiousSect: "Sunni",
    },
    comments:
      "Seeking a partner who is educated, practicing, and has a good sense of humor. Someone who values both families and is willing to make compromises for a healthy relationship.",
    aboutMe:
      "Passionate about health equity and helping communities. I wear hijab and try to incorporate Islam into every part of my life. Love hiking, calligraphy, and trying new cuisines.",
    contactName: "Elder Brother",
    contactPhone: "310-555-0144",
    createdAt: "2025-04-08",
    verified: true,
    phoneVerified: true,
    adminVerified: true,
  },
  {
    id: "7",
    name: "Yusuf T.",
    gender: "Male",
    age: 33,
    height: "5'9",
    residence: "Toronto, Canada",
    relocate: "Open to US or Canada",
    education: "Masters in Business Administration from University of Toronto",
    profession: "Product Manager at a fintech startup",
    legalStatus: "Canadian Citizen",
    maritalStatus: "Divorced",
    children: "1 (lives with ex-spouse)",
    ethnicity: "Somali",
    religiousSect: "Sunni",
    languages: ["Somali", "English", "Arabic"],
    lookingFor: {
      ageRange: "26-33",
      height: "5'3 - 5'7",
      ethnicity: "Any Muslim",
      residence: "North America",
      legalStatus: "Any",
      maritalStatus: "Single / Divorced",
      religiousSect: "Sunni",
    },
    comments:
      "Looking for a partner who is understanding of my situation, kind-hearted, and ready to build a new chapter together. Honesty and communication are most important to me.",
    aboutMe:
      "I'm a practicing Muslim who prays regularly and fasts. I enjoy reading, working out, and spending quality time with my son on weekends. Career-driven but family always comes first.",
    contactName: "Self",
    contactPhone: "416-555-0233",
    createdAt: "2025-04-22",
    verified: true,
    phoneVerified: true,
    adminVerified: false,
  },
  {
    id: "8",
    name: "Zainab H.",
    gender: "Female",
    age: 30,
    height: "5'4",
    residence: "London, UK",
    relocate: "Open to relocation",
    education: "MBBS from King's College London, MRCP in progress",
    profession: "Junior Doctor (Internal Medicine) at NHS",
    legalStatus: "British Citizen",
    maritalStatus: "Single",
    children: "None",
    ethnicity: "Pakistani (Islamabad)",
    religiousSect: "Sunni",
    languages: ["Urdu", "English", "Punjabi"],
    lookingFor: {
      ageRange: "30-37",
      height: "5'8 or taller",
      ethnicity: "Pakistani / South Asian",
      residence: "UK or US",
      legalStatus: "Any legal status",
      maritalStatus: "Single",
      religiousSect: "Sunni",
    },
    comments:
      "Looking for someone patient and understanding of a doctor's schedule. Must be supportive of my career goals while also being family-oriented.",
    aboutMe:
      "Alhamdulillah, I'm a hijabi doctor who loves what she does. I enjoy painting, baking, and going for long walks. I come from a close-knit family and hope to build one of my own InshaAllah.",
    contactName: "Mother",
    contactPhone: "+44-7700-900111",
    createdAt: "2025-04-21",
    verified: true,
    phoneVerified: true,
    adminVerified: true,
  },
  {
    id: "9",
    name: "Ibrahim A.",
    gender: "Male",
    age: 25,
    height: "6'1",
    residence: "Atlanta, GA",
    relocate: "Open to anywhere in the US",
    education: "Bachelors in Mechanical Engineering from Georgia Tech",
    profession: "Mechanical Engineer at an aerospace company",
    legalStatus: "US Citizen",
    maritalStatus: "Single",
    children: "None",
    ethnicity: "Egyptian",
    religiousSect: "Sunni",
    languages: ["Arabic", "English"],
    lookingFor: {
      ageRange: "21-27",
      height: "5'2 - 5'7",
      ethnicity: "Arab / Any Muslim",
      residence: "US based",
      legalStatus: "US Citizen or Green Card",
      maritalStatus: "Single",
      religiousSect: "Sunni",
    },
    comments:
      "Looking for a practicing Muslimah who wears hijab, values her deen, and wants to grow together. Sense of humor is a big plus!",
    aboutMe:
      "Born in Egypt, raised in Atlanta. I love basketball, coding side projects, and volunteering at the masjid. I try to pray all five prayers on time and read Quran daily.",
    contactName: "Father",
    contactPhone: "404-555-0199",
    createdAt: "2025-04-19",
    verified: true,
    phoneVerified: true,
    adminVerified: true,
  },
  {
    id: "10",
    name: "Nadia R.",
    gender: "Female",
    age: 28,
    height: "5'6",
    residence: "Detroit, MI",
    relocate: "Prefer Michigan or nearby states",
    education: "Bachelors in Pharmacy from Wayne State University",
    profession: "Clinical Pharmacist at a hospital",
    legalStatus: "US Citizen",
    maritalStatus: "Single",
    children: "None",
    ethnicity: "Lebanese",
    religiousSect: "Sunni",
    languages: ["Arabic", "English"],
    lookingFor: {
      ageRange: "28-35",
      height: "5'9 or taller",
      ethnicity: "Arab / Any Muslim",
      residence: "US based",
      legalStatus: "US Citizen or Green Card",
      maritalStatus: "Single / Divorced (no children preferred)",
      religiousSect: "Sunni",
    },
    comments:
      "Seeking someone who is established in their career, practices their faith, and values quality time with family. Someone who can make me laugh is a bonus.",
    aboutMe:
      "I'm a proud Lebanese-American Muslimah. I love cooking Middle Eastern food, gardening, and going to the gym. Family gatherings are my favorite part of the week.",
    contactName: "Self",
    contactPhone: "313-555-0277",
    createdAt: "2025-04-17",
    verified: true,
    phoneVerified: true,
    adminVerified: true,
  },
  {
    id: "11",
    name: "Hamza K.",
    gender: "Male",
    age: 27,
    height: "5'8",
    residence: "San Francisco, CA",
    relocate: "Prefer Bay Area",
    education: "Bachelors in Computer Science from UC Berkeley",
    profession: "Software Engineer at a FAANG company",
    legalStatus: "US Citizen",
    maritalStatus: "Single",
    children: "None",
    ethnicity: "Pakistani (Lahore)",
    religiousSect: "Sunni",
    languages: ["Urdu", "Punjabi", "English"],
    lookingFor: {
      ageRange: "23-28",
      height: "5'2 - 5'6",
      ethnicity: "Pakistani / Indian",
      residence: "US based",
      legalStatus: "Any",
      maritalStatus: "Single",
      religiousSect: "Sunni",
    },
    comments:
      "Looking for a partner who is practicing, down-to-earth, and values simple things in life. Someone who wants to grow spiritually and emotionally together.",
    aboutMe:
      "Alhamdulillah, I'm a practicing Muslim who tries to balance deen and career. I enjoy hiking in the Bay Area, watching documentaries, and attending halaqahs at my local masjid.",
    contactName: "Mother",
    contactPhone: "415-555-0188",
    createdAt: "2025-04-16",
    verified: true,
    phoneVerified: true,
    adminVerified: true,
  },
  {
    id: "12",
    name: "Safiya B.",
    gender: "Female",
    age: 23,
    height: "5'1",
    residence: "Minneapolis, MN",
    relocate: "Open to relocation within US",
    education: "Currently pursuing Bachelors in Biology (Pre-Med) at University of Minnesota",
    profession: "Student / Part-time Medical Scribe",
    legalStatus: "US Citizen",
    maritalStatus: "Single",
    children: "None",
    ethnicity: "Somali",
    religiousSect: "Sunni",
    languages: ["Somali", "English", "Arabic"],
    lookingFor: {
      ageRange: "25-31",
      height: "5'7 or taller",
      ethnicity: "Somali / Any Muslim",
      residence: "US or Canada",
      legalStatus: "Citizen or legal resident",
      maritalStatus: "Single",
      religiousSect: "Sunni",
    },
    comments:
      "Looking for someone who supports my educational goals and is patient. Someone who fears Allah and treats people with kindness.",
    aboutMe:
      "Aspiring doctor InshaAllah. I wear niqab and am deeply connected to my faith. I love reading, especially Islamic history, and enjoy spending time outdoors. Very close to my family.",
    contactName: "Elder Sister",
    contactPhone: "612-555-0322",
    createdAt: "2025-04-14",
    verified: false,
    phoneVerified: true,
    adminVerified: false,
  },
  {
    id: "13",
    name: "Tariq M.",
    gender: "Male",
    age: 35,
    height: "5'7",
    residence: "Washington, DC",
    relocate: "Prefer DMV area",
    education: "Juris Doctor from Georgetown University Law Center",
    profession: "Attorney specializing in immigration law",
    legalStatus: "US Citizen",
    maritalStatus: "Divorced",
    children: "None",
    ethnicity: "Indian (Kerala)",
    religiousSect: "Sunni",
    languages: ["Malayalam", "Urdu", "English", "Arabic"],
    lookingFor: {
      ageRange: "27-35",
      height: "Any",
      ethnicity: "South Asian / Any Muslim",
      residence: "US based",
      legalStatus: "Any",
      maritalStatus: "Single / Divorced",
      religiousSect: "Sunni / Any practicing Muslim",
    },
    comments:
      "Second time around, I know exactly what I want: genuine compatibility, shared values, and mutual respect. Not looking for perfection, looking for effort and sincerity.",
    aboutMe:
      "Practicing Muslim, active in community advocacy and legal aid for immigrants. I enjoy traveling, photography, and deep conversations over chai. I believe marriage is a team effort.",
    contactName: "Self",
    contactPhone: "202-555-0411",
    createdAt: "2025-04-13",
    verified: true,
    phoneVerified: true,
    adminVerified: true,
  },
  {
    id: "14",
    name: "Hana S.",
    gender: "Female",
    age: 25,
    height: "5'5",
    residence: "Plano, TX",
    relocate: "Open to Texas or East Coast",
    education: "Bachelors in Accounting from UT Dallas",
    profession: "Senior Associate at a Big 4 accounting firm",
    legalStatus: "H1B Visa",
    maritalStatus: "Single",
    children: "None",
    ethnicity: "Pakistani (Karachi)",
    religiousSect: "Sunni",
    languages: ["Urdu", "English"],
    lookingFor: {
      ageRange: "26-32",
      height: "5'8 or taller",
      ethnicity: "Pakistani",
      residence: "US based",
      legalStatus: "US Citizen or Green Card (for sponsorship stability)",
      maritalStatus: "Single",
      religiousSect: "Sunni",
    },
    comments:
      "Seeking a serious, practicing Muslim man who is ready for marriage and values family. Prefer someone from a similar cultural background.",
    aboutMe:
      "Hardworking and ambitious but also love winding down with a good book or cooking something new. I pray five times and try to attend Islamic classes regularly. Family is everything to me.",
    contactName: "Father",
    contactPhone: "972-555-0355",
    createdAt: "2025-04-11",
    verified: true,
    phoneVerified: true,
    adminVerified: true,
  },
  {
    id: "15",
    name: "Khalid W.",
    gender: "Male",
    age: 30,
    height: "6'0",
    residence: "Miami, FL",
    relocate: "Open to Southeast US",
    education: "Bachelors in Civil Engineering from FIU",
    profession: "Construction Project Manager",
    legalStatus: "Permanent Resident",
    maritalStatus: "Single",
    children: "None",
    ethnicity: "Palestinian",
    religiousSect: "Sunni",
    languages: ["Arabic", "English"],
    lookingFor: {
      ageRange: "24-30",
      height: "5'3 - 5'7",
      ethnicity: "Arab / Any Muslim",
      residence: "US based",
      legalStatus: "Any",
      maritalStatus: "Single",
      religiousSect: "Sunni",
    },
    comments:
      "Looking for a warm, family-oriented partner who appreciates both cultures. Someone who can balance modern life with traditional values.",
    aboutMe:
      "Palestinian born and raised in Miami. I fast Mondays and Thursdays, attend Jummah, and try to be the best version of myself every day. I love the ocean, BBQs with family, and building things with my hands.",
    contactName: "Mother",
    contactPhone: "305-555-0422",
    createdAt: "2025-04-09",
    verified: true,
    phoneVerified: true,
    adminVerified: false,
  },
  {
    id: "16",
    name: "Amira D.",
    gender: "Female",
    age: 32,
    height: "5'3",
    residence: "Boston, MA",
    relocate: "Prefer Northeast US",
    education: "PhD in Biomedical Engineering from MIT (completed)",
    profession: "Research Scientist at a biotech company",
    legalStatus: "US Citizen",
    maritalStatus: "Single",
    children: "None",
    ethnicity: "Moroccan",
    religiousSect: "Sunni",
    languages: ["Arabic", "French", "English"],
    lookingFor: {
      ageRange: "30-38",
      height: "5'8 or taller",
      ethnicity: "Any Muslim",
      residence: "US or Europe",
      legalStatus: "Any",
      maritalStatus: "Single / Divorced",
      religiousSect: "Sunni",
    },
    comments:
      "Education and career delayed my search, but I trust Allah's timing. Looking for a mature, emotionally intelligent man who respects a woman's ambition and faith equally.",
    aboutMe:
      "Moroccan-American scientist by day, amateur chef by night. I wear hijab, pray regularly, and love exploring different cultures. Fluent in three languages and always learning. My idea of a good weekend is a farmers market, a hike, and a home-cooked tagine.",
    contactName: "Self",
    contactPhone: "617-555-0133",
    createdAt: "2025-04-07",
    verified: true,
    phoneVerified: true,
    adminVerified: true,
  },
  {
    id: "17",
    name: "Bilal N.",
    gender: "Male",
    age: 26,
    height: "5'11",
    residence: "Columbus, OH",
    relocate: "Open to Midwest or East Coast",
    education: "Bachelors in Information Systems from Ohio State University",
    profession: "IT Consultant",
    legalStatus: "US Citizen",
    maritalStatus: "Single",
    children: "None",
    ethnicity: "Afghan (Kabul)",
    religiousSect: "Sunni",
    languages: ["Dari", "Pashto", "English"],
    lookingFor: {
      ageRange: "22-27",
      height: "5'1 - 5'5",
      ethnicity: "Afghan / Pakistani / Any Muslim",
      residence: "US based",
      legalStatus: "Any",
      maritalStatus: "Single",
      religiousSect: "Sunni",
    },
    comments:
      "Family-oriented and practicing. My parents are very involved in the search process and would love to connect with like-minded families.",
    aboutMe:
      "Born in Kabul, grew up in Columbus. Alhamdulillah I try to pray on time and keep good company. I enjoy cricket, tech meetups, and helping my community. I value loyalty and sincerity above all.",
    contactName: "Father",
    contactPhone: "614-555-0288",
    createdAt: "2025-04-06",
    verified: true,
    phoneVerified: true,
    adminVerified: true,
  },
  {
    id: "18",
    name: "Ruqayya I.",
    gender: "Female",
    age: 29,
    height: "5'7",
    residence: "Philadelphia, PA",
    relocate: "Open to East Coast",
    education: "Masters in Education from UPenn",
    profession: "High School Teacher (Islamic School)",
    legalStatus: "US Citizen",
    maritalStatus: "Widowed",
    children: "1 daughter (age 3)",
    ethnicity: "African American (Revert)",
    religiousSect: "Sunni",
    languages: ["English", "Arabic (basic)"],
    lookingFor: {
      ageRange: "30-40",
      height: "Any",
      ethnicity: "Any Muslim",
      residence: "US based",
      legalStatus: "Any",
      maritalStatus: "Any",
      religiousSect: "Sunni",
    },
    comments:
      "Looking for a kind, patient man who would accept my daughter as his own. Someone who is practicing, gentle, and wants to be part of a family. Reverts especially welcome.",
    aboutMe:
      "I reverted to Islam 7 years ago, Alhamdulillah. Teaching at an Islamic school has been a blessing. My daughter is my world. I love journaling, gardening, and community iftars. Looking for a fresh start with someone sincere.",
    contactName: "Self",
    contactPhone: "215-555-0499",
    createdAt: "2025-04-05",
    verified: true,
    phoneVerified: true,
    adminVerified: true,
  },
  {
    id: "19",
    name: "Usman G.",
    gender: "Male",
    age: 37,
    height: "5'6",
    residence: "Edison, NJ",
    relocate: "NJ or NY only",
    education: "Bachelors in Business from LUMS Lahore",
    profession: "Restaurant Owner (2 locations in NJ)",
    legalStatus: "US Citizen",
    maritalStatus: "Divorced",
    children: "2 (living with ex-spouse, regular visitation)",
    ethnicity: "Pakistani (Lahore)",
    religiousSect: "Sunni",
    languages: ["Urdu", "Punjabi", "English"],
    lookingFor: {
      ageRange: "28-37",
      height: "Any",
      ethnicity: "Pakistani / Indian",
      residence: "NJ or NY area",
      legalStatus: "Any",
      maritalStatus: "Divorced / Widowed / Single",
      religiousSect: "Sunni",
    },
    comments:
      "I'm honest about my past and looking for someone who can see beyond it. I provide well, Alhamdulillah, and want a companion to share life's blessings with.",
    aboutMe:
      "Self-made business owner. I came to the US with very little and built my restaurants from scratch. I pray five times, give charity regularly, and try to be a good role model for my kids. I value hard work, honesty, and gratitude.",
    contactName: "Brother",
    contactPhone: "732-555-0566",
    createdAt: "2025-04-04",
    verified: true,
    phoneVerified: true,
    adminVerified: true,
  },
  {
    id: "20",
    name: "Layla Q.",
    gender: "Female",
    age: 22,
    height: "5'4",
    residence: "Dearborn, MI",
    relocate: "Prefer Michigan",
    education: "Currently pursuing Bachelors in Marketing at University of Michigan",
    profession: "Student / Social Media Marketing Intern",
    legalStatus: "US Citizen",
    maritalStatus: "Single",
    children: "None",
    ethnicity: "Iraqi",
    religiousSect: "Shia",
    languages: ["Arabic", "English"],
    lookingFor: {
      ageRange: "24-30",
      height: "5'8 or taller",
      ethnicity: "Arab / Any Muslim",
      residence: "Michigan or nearby",
      legalStatus: "US Citizen",
      maritalStatus: "Single",
      religiousSect: "Shia",
    },
    comments:
      "My family is very important in this process. Looking for someone from a good family who is respectful, funny, and has goals in life. Must be Shia.",
    aboutMe:
      "Iraqi-American born and raised in Dearborn. I'm very close to my community and attend majalis regularly. I love creative work — photography, design, and content creation. Also a huge foodie!",
    contactName: "Father",
    contactPhone: "313-555-0611",
    createdAt: "2025-04-03",
    verified: false,
    phoneVerified: false,
    adminVerified: false,
  },
];
