import { Profile } from "./types";

export const mockProfiles: Profile[] = [
  {
    id: "1",
    name: "MSP",
    gender: "Male",
    age: 29,
    height: "5'4",
    residence: "New York, NY",
    relocate: "Open - preference for Chicago, New York, or Texas",
    education:
      "Masters in Supply Chain and Operations Management from University of Illinois at Chicago. Bachelors in Business Administration from Bahria University Karachi.",
    profession:
      "Worked as a logistics coordinator in a fine arts freight forwarding company post graduation. Currently working at a gas station in NY.",
    legalStatus: "Pending green card",
    maritalStatus: "Divorced",
    children: "None",
    ethnicity: "Punjabi (family background), Pakistani (born and raised in Karachi)",
    religiousSect: "Sunni",
    languages: ["Urdu", "English"],
    lookingFor: {
      ageRange: "Around 29",
      height: "Around 5'4",
      ethnicity: "Pakistani / Indian",
      residence: "Anywhere",
      legalStatus: "US Citizen or legal resident",
      maritalStatus: "Single / Divorced / Widowed",
      religiousSect: "Sunni",
    },
    comments:
      "I'm looking for more of a companion and friend who is faithful and fun loving, constantly works on improving religiously, takes husband wife relationship seriously and for the sake of Allah, knows own responsibility and rights of each other for a healthy relationship and tries to balance life in every aspect, and stands by in every part of life both good times and hardships.",
    aboutMe:
      "I'm a single child of my parents, Alhumdullilah by the grace of Allah I try to be punctual about my prayers mostly in masjid, I don't take life too seriously, enjoy life in every and by every halal means, easy going person.",
    contactName: "Cousin Sister",
    contactPhone: "347-341-0176",
    createdAt: "2025-04-20",
    verified: true,
  },
  {
    id: "2",
    name: "Fatima K.",
    gender: "Female",
    age: 26,
    height: "5'3",
    residence: "Chicago, IL",
    relocate: "Open to relocation",
    education: "Bachelors in Computer Science from DePaul University",
    profession: "Software Engineer at a tech company in Chicago",
    legalStatus: "US Citizen",
    maritalStatus: "Single",
    children: "None",
    ethnicity: "Pakistani (Karachi)",
    religiousSect: "Sunni",
    languages: ["Urdu", "English"],
    lookingFor: {
      ageRange: "26-32",
      height: "5'6 or taller",
      ethnicity: "Pakistani / Indian",
      residence: "US based",
      legalStatus: "US Citizen or Green Card holder",
      maritalStatus: "Single",
      religiousSect: "Sunni",
    },
    comments:
      "Looking for someone who is practicing, family-oriented, and has good character. Someone who balances deen and dunya well.",
    aboutMe:
      "Practicing Muslimah who loves to cook, read, and spend time with family. Active in my local community and mosque. Value education and personal growth.",
    contactName: "Mother",
    contactPhone: "312-555-0199",
    createdAt: "2025-04-18",
    verified: true,
  },
  {
    id: "3",
    name: "Ahmed R.",
    gender: "Male",
    age: 31,
    height: "5'10",
    residence: "Houston, TX",
    relocate: "Prefer Texas",
    education:
      "Masters in Electrical Engineering from University of Houston. Bachelors from NUST Islamabad.",
    profession: "Senior Engineer at an oil & gas company",
    legalStatus: "Green Card holder",
    maritalStatus: "Single",
    children: "None",
    ethnicity: "Pathan, Pakistani (from Peshawar)",
    religiousSect: "Sunni",
    languages: ["Pashto", "Urdu", "English"],
    lookingFor: {
      ageRange: "24-29",
      height: "5'2 - 5'6",
      ethnicity: "Pakistani",
      residence: "US based",
      legalStatus: "Any",
      maritalStatus: "Single",
      religiousSect: "Sunni",
    },
    comments:
      "Looking for a practicing Muslimah who values family, is kind-hearted, and supportive. Someone who wants to build a life together based on Islamic principles.",
    aboutMe:
      "Alhamdulillah, I pray five times daily and try to attend Fajr at the masjid. I enjoy outdoor activities, hiking, and traveling. Family is very important to me.",
    contactName: "Father",
    contactPhone: "832-555-0177",
    createdAt: "2025-04-15",
    verified: false,
  },
  {
    id: "4",
    name: "Aisha M.",
    gender: "Female",
    age: 24,
    height: "5'5",
    residence: "Dallas, TX",
    relocate: "Open to relocation within US",
    education: "Bachelors in Nursing from UT Arlington",
    profession: "Registered Nurse at a hospital in Dallas",
    legalStatus: "US Citizen",
    maritalStatus: "Single",
    children: "None",
    ethnicity: "Indian (Hyderabadi)",
    religiousSect: "Sunni",
    languages: ["Urdu", "Hindi", "English"],
    lookingFor: {
      ageRange: "26-33",
      height: "5'8 or taller",
      ethnicity: "Indian / Pakistani",
      residence: "US based",
      legalStatus: "US Citizen or Green Card holder",
      maritalStatus: "Single",
      religiousSect: "Sunni",
    },
    comments:
      "Seeking a partner who is God-fearing, respectful, and family-oriented. Someone who understands the importance of communication and is willing to grow together in faith.",
    aboutMe:
      "Alhamdulillah, I am a practicing Muslimah. I love my profession and caring for others. In my free time, I enjoy reading Islamic books, cooking, and spending time with family.",
    contactName: "Father",
    contactPhone: "469-555-0188",
    createdAt: "2025-04-12",
    verified: true,
  },
  {
    id: "5",
    name: "Omar S.",
    gender: "Male",
    age: 28,
    height: "5'11",
    residence: "Jersey City, NJ",
    relocate: "Open - NY/NJ area preferred",
    education: "Bachelors in Finance from Rutgers University",
    profession: "Financial Analyst at a bank in Manhattan",
    legalStatus: "US Citizen",
    maritalStatus: "Single",
    children: "None",
    ethnicity: "Bengali (from Dhaka)",
    religiousSect: "Sunni",
    languages: ["Bengali", "English"],
    lookingFor: {
      ageRange: "23-28",
      height: "5'2 - 5'5",
      ethnicity: "Bengali / South Asian",
      residence: "Northeast US",
      legalStatus: "US Citizen or Green Card holder",
      maritalStatus: "Single",
      religiousSect: "Sunni",
    },
    comments:
      "Looking for someone humble, caring, and who puts their trust in Allah. Wants to build a home filled with love, respect, and Islamic values.",
    aboutMe:
      "Born and raised in the US. Active in my local masjid and youth group. I enjoy playing soccer, reading, and volunteering. I value honesty and good character above all.",
    contactName: "Mother",
    contactPhone: "201-555-0166",
    createdAt: "2025-04-10",
    verified: true,
  },
  {
    id: "6",
    name: "Mariam J.",
    gender: "Female",
    age: 27,
    height: "5'2",
    residence: "Los Angeles, CA",
    relocate: "Prefer West Coast",
    education: "Masters in Public Health from UCLA",
    profession: "Public Health Researcher",
    legalStatus: "US Citizen",
    maritalStatus: "Single",
    children: "None",
    ethnicity: "Pakistani (Lahore)",
    religiousSect: "Sunni",
    languages: ["Punjabi", "Urdu", "English"],
    lookingFor: {
      ageRange: "27-34",
      height: "5'7 or taller",
      ethnicity: "Pakistani / South Asian",
      residence: "US based",
      legalStatus: "US Citizen or Green Card holder",
      maritalStatus: "Single / Divorced",
      religiousSect: "Sunni",
    },
    comments:
      "Seeking a partner who is educated, practicing, and has a good sense of humor. Someone who values both families and is willing to make compromises for a healthy relationship.",
    aboutMe:
      "Passionate about health equity and helping communities. I wear hijab and try to incorporate Islam into every part of my life. Love hiking, calligraphy, and trying new cuisines.",
    contactName: "Elder Brother",
    contactPhone: "310-555-0144",
    createdAt: "2025-04-08",
    verified: true,
  },
];
